#!/bin/bash

# set ip as env var - this is important for running the jmeter tests in a distributed style
echo "export LOCALIP=$(hostname -i)" >> /etc/bash.bashrc
source /etc/bash.bashrc

#declare some variables
jmeter_version=5.3
jmeter_home=/home/ubuntu/apache-jmeter-$jmeter_version

# update the ubuntu OS
sudo apt-get update -y

#clean out any dangling files in any repos
sudo apt-get clean

# Update the OS
sudo apt-get update

# Install wget to download jmeter in a few moments
sudo apt-get -qy install wget

#install telnet to help with SSH connections
sudo apt-get -qy install telnet

#Install ping to help with networking
sudo apt-get -qy install iputils-ping

#install unzip to unzip the jmeter archive we're about to download
sudo apt-get -qy install unzip

#navigate to the ubuntu users home dir
cd /home/ubuntu

# download jmeter latest based on the version number in the jmeter_version var
sudo wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$jmeter_version.tgz

#unzip the archive
sudo tar -xzf apache-jmeter-$jmeter_version.tgz

#delete the archive file (leaving only the unzipped files)
sudo rm apache-jmeter-$jmeter_version.tgz

#update the OS againn to make sure everything is as up to date as it can be
sudo apt-get update -y

#install htop for performance monitoring
sudo apt install htop